language: node_js
node_js:
  - '8'
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=production PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - yarn
  - yarn run build:client
