language: node_js
node_js:
  - '16'
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=production PORT=3003
install:
  - npm install --global cross-env
  - yarn
  - cd client
  - yarn add --dev eslint-config-airbnb-base
  - yarn add --dev eslint-config-prettier
  - yarn
  - yarn build
