language: node_js
node_js:
  - '16'
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=production PORT=3003
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install --global cross-env
  - yarn global add install-peerdeps
  - cd client
  - install-peerdeps --dev eslint-config-airbnb
  - install-peerdeps --dev eslint-config-airbnb-base
  - yarn run build
