language: node_js
node_js:
  - '16'
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=production PORT=3003
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - yarn
  - cd client
  - yarn
  - yarn build
