"use strict";
exports.__esModule = true;
exports.app = void 0;
var body_parser_1 = require("body-parser");
var compression_1 = require("compression");
var cors_1 = require("cors");
var express_1 = require("express");
var helmet_1 = require("helmet");
var morgan_1 = require("morgan");
var advertisingRoute_1 = require("./components/Advertising/advertisingRoute");
var ping_1 = require("./components/ping");
var restaurantRoute_1 = require("./components/restaurant/restaurantRoute");
require('dotenv').config();
var app = express_1["default"]();
exports.app = app;
app.enable('trust proxy');
app.use(cors_1["default"]());
app.use(compression_1["default"]());
app.use(body_parser_1.json());
app.use(morgan_1["default"]('dev'));
app.use(helmet_1["default"]());
app.use(ping_1.pingRouter);
app.use(restaurantRoute_1.indexOfRestaurants);
app.use(advertisingRoute_1.indexOfAdvertising);
